on:
  push:
    branches:
      - main
jobs:
  Deploy-Cloud-Function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          region: us-central1
          credentials: ${{ secrets.GCP_SA_KEY }}
          name: customer-reminder
          source_dir: ./job
          entry_point: RunJob
          runtime: go113
